### ISSUE TITLE
Background image (AVS page)

### ISSUE THREAD

**Issue by niiicolai** [niiicolai/digital-poster-prototypes#15]
- import of avs bgg image
- draw background image

Find background images at [Google drive P0 folder](https://drive.google.com/drive/folders/1or44oez8s7Ax_M9QptMJhQFQ604UA-jo)

**Comment by niiicolai** [comment]
@marcusottosen har du implementeret det her?

**Comment by marcusottosen** [comment]
Var de ikke færdige? Eller var det ment til at implementere det i koden?

**Comment by niiicolai** [comment]
@marcusottosen yes. Alt her inde er specifikt til koden
